export const employeesMasterData = [
    {
        employee_age: 61,
        employee_name: "Tiger Nixon",
        employee_salary: 320800,
        id: 1,
        profile_image: "",
    },
    {
        employee_age: 61,
        employee_name: "Richard Nixon",
        employee_salary: 320800,
        id: 2,
        profile_image: "",
    },
    {
        employee_age: 37,
        employee_name: "Henry Ben",
        employee_salary: 320800,
        id: 3,
        profile_image: "",
    },
    {
        employee_age: 44,
        employee_name: "Mark",
        employee_salary: 320800,
        id: 4,
        profile_image: "",
    },
    {
        employee_age: 34,
        employee_name: "Mark Toen",
        employee_salary: 320800,
        id: 5,
        profile_image: "",
    },
    {
        employee_age: 30,
        employee_name: "Albert",
        employee_salary: 320800,
        id: 6,
        profile_image: "",
    },
    {
        employee_age: 40,
        employee_name: "Alex",
        employee_salary: 320800,
        id: 7,
        profile_image: "",
    },
    {
        employee_age: 40,
        employee_name: "Neymer",
        employee_salary: 320800,
        id: 8,
        profile_image: "",
    },
    {
        employee_age: 63,
        employee_name: "Patrick",
        employee_salary: 320800,
        id: 9,
        profile_image: "",
    },
    {
        employee_age: 36,
        employee_name: "Paul",
        employee_salary: 320800,
        id: 10,
        profile_image: "",
    },
    {
        employee_age: 54,
        employee_name: "Jio pal",
        employee_salary: 320800,
        id: 11,
        profile_image: "",
    },
    {
        employee_age: 45,
        employee_name: "Test user",
        employee_salary: 320800,
        id: 12,
        profile_image: "",
    },
    {
        employee_age: 61,
        employee_name: "Jaky",
        employee_salary: 320800,
        id: 13,
        profile_image: "",
    },
    {
        employee_age: 35,
        employee_name: "Einestien",
        employee_salary: 320800,
        id: 14,
        profile_image: "",
    },
    {
        employee_age: 30,
        employee_name: "Neuton",
        employee_salary: 320800,
        id: 15,
        profile_image: "",
    },
]